import type { ApiCard, ApiColumn } from '../api/board';
import { columnRole, contextLabelFor, type Layout, type Role, ROLE_FOLDERS, WEEKLY_REVIEW_NOTE } from './layout';

// The list overview notes at the root of the GTD folder. They are regenerated after
// every sync from the board, so they are read-only views; the card notes are the data.

export const FM_OVERVIEW = 'gtdbrain_overview';

const GENERATED_NOTICE =
	'> [!info] Generated by GTD Brain on every sync — edits here are overwritten. Edit the notes in the list folders instead.';

export type OverviewInput = {
	layout: Layout;
	/** card id → vault path of its note (only live cards that have a note) */
	pathById: Map<string, string>;
};

function link(path: string): string {
	const base = path.split('/').pop() ?? path;
	return `[[${base.replace(/\.md$/, '')}]]`;
}

function liveCardsIn(col: ApiColumn, layout: Layout): ApiCard[] {
	return col.cardIds.map((id) => layout.cardsById.get(id)).filter((c): c is ApiCard => !!c && !c.archived);
}

function header(role: string, title: string, subtitle: string): string {
	return `---\n${FM_OVERVIEW}: ${role}\n---\n# ${title}\n\n${subtitle}\n\n${GENERATED_NOTICE}\n\n`;
}

function simpleList(cards: ApiCard[], input: OverviewInput): string {
	if (cards.length === 0) return '_Nothing here._\n';
	return cards.map((c) => `- ${input.pathById.has(c.id) ? link(input.pathById.get(c.id)!) : c.title}`).join('\n') + '\n';
}

export function renderOverview(role: Role, col: ApiColumn, input: OverviewInput): string {
	const { layout } = input;
	const cards = liveCardsIn(col, layout);
	const folder = layout.folderByColumn.get(col.id)?.split('/').pop() ?? col.label;
	switch (role) {
		case 'inbox':
			return (
				header(role, col.label, `Capture here, clarify later. New notes in the **${folder}** folder land in your GTD Brain inbox on the next sync.`) +
				simpleList(cards, input)
			);
		case 'next': {
			let out = header(role, col.label, 'What you can do next, grouped by context. Set `context:` in a note to move it between groups.');
			const groups = new Map<string, ApiCard[]>();
			for (const c of cards) {
				const key = c.context ?? '';
				if (!groups.has(key)) groups.set(key, []);
				groups.get(key)!.push(c);
			}
			const order = [...layout.contexts.map((c) => c.id).filter((id) => groups.has(id)), ...[...groups.keys()].filter((k) => k && !layout.contexts.some((c) => c.id === k)), ...(groups.has('') ? [''] : [])];
			if (cards.length === 0) out += '_Nothing here._\n';
			for (const key of order) {
				const label = key ? contextLabelFor(key, layout.contexts) : 'No context';
				out += `## ${label}\n\n`;
				for (const c of groups.get(key) ?? []) {
					const project = c.projectId ? layout.cardsById.get(c.projectId) : undefined;
					const projectLink = project && input.pathById.has(project.id) ? ` · ${link(input.pathById.get(project.id)!)}` : project ? ` · ${project.title}` : '';
					out += `- ${input.pathById.has(c.id) ? link(input.pathById.get(c.id)!) : c.title}${projectLink}\n`;
				}
				out += '\n';
			}
			return out;
		}
		case 'projects': {
			let out = header(role, col.label, 'Outcomes that take more than one step. Every project should have at least one next action.');
			if (cards.length === 0) out += '_Nothing here._\n';
			const nextCol = layout.columns.find((c) => c.kind === 'next');
			const nextIds = new Set(nextCol?.cardIds ?? []);
			for (const p of cards) {
				const actions = [...layout.cardsById.values()].filter((c) => c.projectId === p.id && !c.archived && nextIds.has(c.id));
				out += `## ${input.pathById.has(p.id) ? link(input.pathById.get(p.id)!) : p.title}\n\n`;
				if (actions.length === 0) out += '- ⚠️ No next action\n';
				for (const a of actions) {
					const ctx = a.context ? ` (${contextLabelFor(a.context, layout.contexts)})` : '';
					out += `- ${input.pathById.has(a.id) ? link(input.pathById.get(a.id)!) : a.title}${ctx}\n`;
				}
				out += '\n';
			}
			return out;
		}
		case 'waiting': {
			let out = header(role, col.label, 'Delegated and waiting on someone else. Set `who:` and `since:` in a note to fill the table.');
			if (cards.length === 0) return out + '_Nothing here._\n';
			out += '| Item | Who | Since |\n| --- | --- | --- |\n';
			for (const c of cards) {
				out += `| ${input.pathById.has(c.id) ? link(input.pathById.get(c.id)!) : c.title} | ${c.who ?? ''} | ${c.since ?? ''} |\n`;
			}
			return out;
		}
		case 'someday':
			return header(role, col.label, 'Incubating. Review during the weekly review and promote what is ready.') + simpleList(cards, input);
		default:
			return header(role, col.label, `Cards in the **${folder}** list.`) + simpleList(cards, input);
	}
}

export function overviewNoteName(role: Role, col: ApiColumn, layout: Layout): string {
	const folder = layout.folderByColumn.get(col.id)?.split('/').pop();
	return role === 'other' ? (folder ?? col.label) : ROLE_FOLDERS[role];
}

export function overviewsFor(layout: Layout, pathById: Map<string, string>): { path: string; content: string }[] {
	const input = { layout, pathById };
	return layout.columns.map((col) => {
		const role = columnRole(col, layout.columns);
		return { path: `${layout.root}/${overviewNoteName(role, col, layout)}.md`, content: renderOverview(role, col, input) };
	});
}

// Created once by "Set up GTD folders"; never overwritten, it is the user's checklist.
export function weeklyReviewNote(root: string): { path: string; content: string } {
	const l = (name: string) => `[[${name}]]`;
	return {
		path: `${root}/${WEEKLY_REVIEW_NOTE}.md`,
		content: `# Weekly review

A trusted system needs one honest look a week. Work top to bottom; tick the boxes, then clear them for next week.

## Get clear
- [ ] Collect loose papers, receipts and notes into ${l(ROLE_FOLDERS.inbox)}
- [ ] Empty your head: write every open loop as its own note in ${l(ROLE_FOLDERS.inbox)}
- [ ] Process ${l(ROLE_FOLDERS.inbox)} to zero — move each note to ${l(ROLE_FOLDERS.next)}, ${l(ROLE_FOLDERS.projects)}, ${l(ROLE_FOLDERS.waiting)} or ${l(ROLE_FOLDERS.someday)}, or delete it

## Get current
- [ ] Review ${l(ROLE_FOLDERS.next)}: cross off what is done, fix anything that is not a physical next step
- [ ] Review ${l(ROLE_FOLDERS.projects)}: every project has a next action
- [ ] Review ${l(ROLE_FOLDERS.waiting)}: chase anything overdue, record what came back
- [ ] Review the calendar: past week for loose ends, upcoming weeks for what needs preparation

## Get creative
- [ ] Review ${l(ROLE_FOLDERS.someday)}: promote what is ready, drop what no longer matters
- [ ] Any new ideas? Capture them to ${l(ROLE_FOLDERS.inbox)}

_Synced with your GTD Brain board — the same lists on the web, iOS, Android and your AI assistant._
`,
	};
}
